import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';

import { BrandGradient } from '@/components/brand-gradient';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { useE2EKeys } from '@/lib/crypto/e2e-context';

export default function E2ESetupScreen() {
  const { status, recoveryPhrase, setupNew, acknowledgeRecoveryPhrase } = useE2EKeys();
  const [confirmed, setConfirmed] = useState(false);
  const [progress, setProgress] = useState(0);
  const requestedRef = useRef(false);

  useEffect(() => {
    if (recoveryPhrase || requestedRef.current) return;
    requestedRef.current = true;
    setupNew(setProgress);
  }, [recoveryPhrase, setupNew]);

  function handleContinue() {
    acknowledgeRecoveryPhrase();
    router.back();
  }

  return (
    <ThemedView style={styles.container}>
      <ThemedText type="title" style={styles.heading}>
        Save your recovery phrase
      </ThemedText>
      <ThemedText style={styles.body}>
        This unlocks your encrypted messages on any device — it&apos;s shown only once, generated by the app so it
        can&apos;t be a guessable password. Write it down somewhere safe.
      </ThemedText>

      {!recoveryPhrase ? (
        <ActivityIndicator style={styles.spinner} />
      ) : (
        <View style={styles.phraseBox}>
          <ThemedText style={styles.phrase} selectable>
            {recoveryPhrase}
          </ThemedText>
        </View>
      )}

      <Pressable
        onPress={() => setConfirmed((c) => !c)}
        style={styles.checkboxRow}
        disabled={!recoveryPhrase}
        accessibilityRole="checkbox"
        accessibilityState={{ checked: confirmed }}>
        {confirmed ? (
          <BrandGradient style={[styles.checkbox, styles.checkboxFilled]}>
            <ThemedText style={styles.checkboxMark}>✓</ThemedText>
          </BrandGradient>
        ) : (
          <View style={styles.checkbox} />
        )}
        <ThemedText style={styles.checkboxLabel}>I&apos;ve saved this phrase somewhere safe</ThemedText>
      </Pressable>

      <Pressable onPress={handleContinue} disabled={!confirmed} style={[styles.button, { opacity: confirmed ? 1 : 0.4 }]}>
        <BrandGradient style={styles.buttonFill}>
          <ThemedText style={styles.buttonLabel} lightColor="#fff" darkColor="#fff">
            Continue
          </ThemedText>
        </BrandGradient>
      </Pressable>

      {status === 'needs-setup' && !recoveryPhrase && (
        <ThemedText style={styles.hint}>
          Setting up encryption for this hub… this is CPU-intensive and can take up to a minute on some phones.
          {progress > 0 ? ` ${Math.round(progress * 100)}%` : ''}
        </ThemedText>
      )}
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 60,
  },
  heading: {
    fontSize: 22,
    marginBottom: 10,
  },
  body: {
    opacity: 0.7,
    lineHeight: 21,
    marginBottom: 24,
  },
  spinner: {
    marginVertical: 32,
  },
  phraseBox: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#8884',
    borderRadius: 12,
    padding: 20,
    marginBottom: 24,
  },
  phrase: {
    fontSize: 19,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 28,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 24,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#8886',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  checkboxFilled: {
    borderColor: 'transparent',
  },
  checkboxMark: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  checkboxLabel: {
    fontSize: 14.5,
  },
  button: {
    height: 52,
    borderRadius: 12,
    overflow: 'hidden',
  },
  buttonFill: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonLabel: {
    fontSize: 16,
    fontWeight: '600',
  },
  hint: {
    marginTop: 16,
    textAlign: 'center',
    opacity: 0.5,
    fontSize: 12,
  },
});
